CREATE TABLE Client (
	NIF CHAR(10) CONSTRAINT PK_Client PRIMARY KEY,
	birthDate Date
		CONSTRAINT NN_ClientBirthDate NOT NULL,
	name VARCHAR2(33 CHAR)
		CONSTRAINT NN_ClientName NOT NULL,
	surname VARCHAR2(80 CHAR)
		CONSTRAINT NN_ClientSurnames NOT NULL,
	address VARCHAR2(100 CHAR)
		CONSTRAINT NN_ClientAddress NOT NULL,
	phone VARCHAR2(12 CHAR)
		CONSTRAINT NN_ClientPhone NOT NULL,
	eMail VARCHAR2(80 CHAR)
); 