CREATE TABLE Has (
	NIF CHAR(10),
	accountNumber INTEGER,
	CONSTRAINT PK_Has PRIMARY KEY (NIF, accountNumber),
	CONSTRAINT FK_ClientHas FOREIGN KEY (NIF) REFERENCES Client(NIF),
	CONSTRAINT FK_AccountHas FOREIGN KEY (loanCode) REFERENCES Account(number)
);